version: "3.7"
services: 
  mongodb:
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./seed-data:/seed-data
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    #   - MONGO_INITDB_ROOT_USERNAME="user" 
    #   - MONGO_INITDB_ROOT_PASSWORD="pass"
      - MONGO_INITDB_DATABASE="test"
    # command: ["mongod", "--auth"]
  mongo-seed:
    image: mongo:latest
    depends_on:
     - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    volumes:
      - ./seed-data:/seed-data
    command:
      bash -c "sleep 60 && mongoimport --host mongodb --port 27017 --db test --collection bird --mode upsert --type json --file /seed-data/seed-data.json --jsonArray"