version: "3.7"
services: 
  mongodb:
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    #   - MONGO_INITDB_ROOT_USERNAME="user" 
    #   - MONGO_INITDB_ROOT_PASSWORD="pass"
    #   - MONGO_INITDB_DATABASE="test"
    # command: ["mongod", "--auth"]